# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 947ec40146c25e8bdd84461cf886d759027d32ac2c5d1d45d634455a92c59eca20d1b1b1d59f681428c71481345e1e81d80c0e4f8bf395972077feab1314f213

test:
  secret_key_base: 5b7d3197af7b90e163d1d89cf40105894e10832097be099b51bf08bbe290b6f347a26402be84367db3e6ac0bb5439fabd9eac9d7c8adefda1ef923b2b55bc519

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
